version: 0.0
os: linux
permissions:
  - object:
      pattern: "**"
      owner: ec2-user
      group: ec2-user
files:
  - source: .
    destination: /home/ec2-user/app
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: roots
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root